### ISSUE TITLE
"About" page needs editing & additions

### ISSUE THREAD

**Issue by toribr** [cityofaustin/grackl#114]
Page needs reviewing by editor. Also needs copy about project stages as well as copy which addresses the city goals.

**Comment by mateoclarke** [comment]
https://grackle.austintexas.io/about/

**Comment by mateoclarke** [comment]
@danielhonker is going to take a crack at editing content and loop in Laura Trujillo for content work shopping.

**Comment by danielhonker** [comment]
Updated copy ready for publishing: https://docs.google.com/document/d/1jSx8SYGzSdj490tvXRvd0ZNPoozwtMH-s-XB5KCSltk/edit#
