### ISSUE TITLE
Limit City Goals per project

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/grackl#116]
- currently we allow them to select all that apply.
- let's let them pick more than one, but not more than 2

**Comment by danielhonker** [comment]
Create secondary goal field. Keep primary goal field.

**Comment by danielhonker** [comment]
@mateoclarke Airtable now has Primary Strategic Outcome field and Secondary Strategic Outcome field.

**Comment by mateoclarke** [comment]
We need to update how this is displayed so that it will be "Primary Goal, Secondary Goal"
